### ISSUE TITLE
Search algorithm fails if the search phrases have identical leading words

### ISSUE THREAD

**Issue by JStateson** [JStateson/PDF-PhraseFinder#1]
Phrases are matched sequentially and once found there is no additional searching.  For example:\
High Speed USB
High Speed SATA

If the phrase High Speed SATA occurs first in the document, then it will not be found because "High Speed" from the USB phrase was found and then discarded as USB did not match SATA.
 
Solution: the words need to be pushed back into the document before the next pattern is matched.  Alternately the words from the document must be examined using a sliding window where the windows size is the length (in words) of the largest phrase.

**Comment by enduringwriter** [comment]
maybe this might help:

using System;
using System.Collections.Generic;

class Program
{
    static void Main()
    {
        string textContent = "High Speed SATA is faster than High Speed USB.";
        string[] phrasesToSearch = { "High Speed USB", "High Speed SATA" };

        bool result = SearchForPhrases(textContent, phrasesToSearch);
        Console.WriteLine(result); // Output: True
    }

    static bool SearchForPhrases(string text, string[] phrases)
    {
        string[] words = text.Split(new[] { ' ', '.', ',', '!', '?' }, StringSplitOptions.RemoveEmptyEntries);
        HashSet<string> foundPhrases = new HashSet<string>();

        for (int i = 0; i < words.Length; i++)
        {
            for (int j = i + 1; j <= words.Length; j++)
            {
                string currentWord = string.Join(" ", words, i, j - i);
                foreach (string phrase in phrases)
                {
                    if (phrase.Equals(currentWord, StringComparison.OrdinalIgnoreCase))
                    {
                        foundPhrases.Add(phrase);
                    }
                }
            }
        }

        return foundPhrases.Count == phrases.Length;
    }
}

**Comment by enduringwriter** [comment]
this one is written based on your code:

private bool bMatchWord(string word, int iPage, int jMax, ref int jWord, ref bool bError)
{
    int n;
    string strTemp = "";
    if (word == null) return false;
    if (word.Length < 2) return false;
    if (cbIgnoreCase.Checked) word = word.ToLower();
    
    for (int i = 0; i < NumPhrases; i++)
    {
        if (!phlist[i].Select) continue;
        if (word == WorkingPhrases[i])
        {
            n = phlist[i].nFollowing;
            if (n == 0)
            {
                phlist[i].IncMatch();
                phlist[i].AddPage(iPage);
                return true;
            }

            // Sliding window approach to check all possible matches
            int startPos = jWord;
            int endPos = jWord + n;
            for (int k = startPos; k < endPos; k++)
            {
                if (k >= jMax) break; // Avoid reading past the end of the page or ThisDoc
                word = GetThisWord(k, jMax, iPage, ref bError);
                if (bError) return false; // Some PDFs are corrupted

                if (cbIgnoreCase.Checked) word = word.ToLower();
                strTemp = phlist[i].strInSeries[k - startPos + 1]; // Check for the corresponding phrase word
                if (cbIgnoreCase.Checked) strTemp = strTemp.ToLower();
                if (strTemp != word) break; // If there is a mismatch, stop checking this phrase
            }

            if (endPos - startPos == n) // If all words in the phrase match, consider it a successful match
            {
                phlist[i].IncMatch();
                phlist[i].AddPage(iPage);
                jWord = endPos; // Move the word index to the end of the matched phrase
                return true;
            }
        }
    }

    return false;
}

**Comment by JStateson** [comment]
Fixed by joining all words together into an entire page that was then searched.  Phrases are sorted by size so the largest phrases is found first and then removed. The search is repeated to remove all the identical phrases before the next (smaller size) phrase is found.
Previously "high speed" would prevent "high speed usb" from being found.
